### ISSUE TITLE
henear lines in interactive mode

### ISSUE THREAD

**Issue by tdwilkinson** [jradavenport/spectra#25]
The plot that pops up in interactive mode show spectral lines increasing in wavelengh to the right. However, the arcs that are linked for comparison show spectral lines increasing in wavelength to the left. Usually, I think it would be flipped after the identify step in IRAF.

**Comment by jradavenport** [comment]
_SPECTRA_ always shows the lines with increasing wavelength. The APO documentation only shows it in increasing pixel number. This is because the wavelength solution of the RED chip on DIS is backwards in pixel space, which _SPECTRA_ knows and adjusts correctly.

Interestingly (frustratingly), the header in the DIS RED channel doesn't indicate in any way the wavelength solution is backwards.

**Comment by tdwilkinson** [comment]
![interactive_henear_2](https://cloud.githubusercontent.com/assets/11761321/7260087/84c59530-e81c-11e4-8527-4d493f0b8844.png)

Here's just a comparison for what I meant. You are right that APO shows it in pixel space, and the wavelength solution is backwards. In processing, the pictures didn't quite match, so I had to mirror one to match the lines.

**Comment by jradavenport** [comment]
well, what we _should_ do is make new versions of the HeNeAr images that are 

1) in the right wavelength order
2) made in Python so the images look better (the current ones are made in IDL, and saved with screenshot instead of high res)
